#!/bin/bash

codec="h264"
mkdir ${codec}
mkdir out
for i in `seq 5 20`; do
	avconv -benchmark -r 25 -i imagenes/Cubo%02d.png -g 50 -refs 0 -r ${i} -codec:v ${codec} ${codec}/cub_${codec}_g50_ref0_r${i}.avi > log	2>&1
done
