#!/bin/bash

end_search_mode_list="fastSearch fullSearch"
search_mode_list="tileSearch pixelSearch"
compare_mode_list="mad ssd"
encode_mode_list="realistic regular"
gop_mode_list="2 3 4 5"
seek_mode_list="0 1 2 3 4 5 6 7 8 9 10"
tiles_list="8 10 15 16"
video="Cubo.zip"

for end_search in $end_search_mode_list; do
	for search_mode in $search_mode_list; do
        for compare_mode in $compare_mode_list; do
            for encode_mode in $encode_mode_list; do
                for gop_mode in $gop_mode_list; do
                    for seek_mode in $seek_mode_list; do
                        for tile in $tiles_list; do



for codec in $codec_list; do
	echo ${codec}
	[ -f cub_${codec}.avi ] && rm cub_${codec}.avi
	avconv -benchmark -r 25 -i imagenes/Cubo%02d.png -codec:v ${codec} cub_${codec}.avi > ${codec}.out 2>&1
	cat ${codec}.out | grep bench
done
