#!/bin/bash

methods="dia hex umh full"

rm -r result
rm -r outs

mkdir result
mkdir outs
for method in $methods; do
	avconv -benchmark -r 25 -i imagenes/Cubo%02d.png -g 50 -refs 0 -r 25 -codec:v h264 -me_method ${method} result/cub_${method}.avi > outs/${method}.out 2>&1
	cat outs/${method}.out | grep bench
done
